const form = document.querySelector('#money-checkup');
if (form) {
  const steps = [...form.querySelectorAll('.checkup__step')], next = form.querySelector('.checkup__next'), back = form.querySelector('.checkup__back'), error = form.querySelector('.checkup__error'), result = document.querySelector('#checkup-result');
  let current = 0;
  const show = index => { steps.forEach((step,i)=>{step.hidden=i!==index;}); current=index; back.hidden=current===0; error.hidden=true; next.textContent=current===steps.length-1?'See my next move →':'Next →'; };
  const recommendation = () => {
    const data=Object.fromEntries(new FormData(form));
    if(data.bills!=='yes') return {stage:'Survive',title:'Make the month reliable first.',body:'Investing can stay on your horizon. Your strongest next move is to see what each paycheck must cover so a bill does not force you to borrow or sell investments.',primary:['/moneyhub/money-reset.html?focus=paycheck','Do the 10-minute Money Reset'],secondary:['/moneyhub/start-here/why-invest.html','Keep learning: why invest at all?']};
    if(data.buffer==='none') return {stage:'Stabilize',title:'Build the first layer of breathing room.',body:data.match==='available'?'A starter cash cushion can protect you from small surprises. You may also want to learn enough about your workplace match to avoid leaving compensation unused.':'A starter cash cushion can keep an ordinary surprise from becoming new debt or forcing you to sell an investment.',primary:['/moneyhub/step3-emergency-fund.html','Build your first cash cushion'],secondary:['/moneyhub/investing/account-types.html','Learn about investing accounts']};
    if(data.debt==='high') return {stage:'Stabilize',title:'Make expensive debt compete for your next dollar.',body:'You do not have to stop learning about investing. But high interest is a certain cost, while market returns are uncertain. Build a payoff plan alongside any decision about an employer match.',primary:['/moneyhub/step2-high-interest-debt.html','Make a debt payoff plan'],secondary:['/moneyhub/investing/','Keep building investing knowledge']};
    if(data.horizon!=='yes') return {stage:'Stabilize',title:'Give near-term money a safer job.',body:'Money you may need within five years generally should not depend on stock-market timing. Separate that goal from money intended for decades in the future.',primary:['/moneyhub/step3-emergency-fund.html','Plan your near-term cushion'],secondary:['/moneyhub/investing/staying-invested.html','Understand the long-term horizon']};
    return {stage:'Grow',title:'Your runway is ready for the next investing step.',body:data.match==='available'?'Start by understanding your workplace match, then choose a simple contribution you can repeat. Your foundation helps you keep going when markets or life get uncomfortable.':'Choose the right account, a simple diversified approach, and a contribution you can repeat. Your foundation helps you stay invested.',primary:['/moneyhub/investing/','Build your investing plan'],secondary:['/moneyhub/step5-automation.html','Automate the habit']};
  };
  next.addEventListener('click',()=>{ if(!steps[current].querySelector('input:checked')){error.hidden=false;return;} if(current<steps.length-1){show(current+1);return;} const rec=recommendation();form.hidden=true;result.innerHTML=`<span class="checkup__stage">${rec.stage}</span><h3>${rec.title}</h3><p>${rec.body}</p><div class="checkup__actions"><a href="${rec.primary[0]}">${rec.primary[1]} →</a><a href="${rec.secondary[0]}">${rec.secondary[1]}</a></div><button type="button" class="checkup__restart">Retake checkup</button>`;result.hidden=false;result.focus();result.querySelector('.checkup__restart').addEventListener('click',()=>{form.reset();result.hidden=true;form.hidden=false;show(0);});});
  back.addEventListener('click',()=>show(Math.max(0,current-1))); form.addEventListener('change',()=>{error.hidden=true;});
}
