import { renderHead } from './page-head.mjs';
import { esc } from '../../resources/js/esc.mjs';
const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];
function prettyDate(iso) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso || '');
  return m ? `${MONTHS[+m[2]-1]} ${+m[3]}, ${m[1]}` : '';
}
const BADGE = { 'market-take':'GOJO','deep-dive':'GOJO','journal':'GOJO','wealth':'WEALTH','health':'HEALTH' };

function crumbs(items) {
  return items.map(c => c.href
    ? `<li><a href="${esc(c.href)}">${esc(c.label)}</a></li>`
    : `<li aria-current="page">${esc(c.label)}</li>`).join('');
}

export function renderArticle(f) {
  const kicker = [BADGE[f.type] || (f.section || '').toUpperCase(), f.ticker].filter(Boolean).map(esc).join(' · ');
  const dateBits = [prettyDate(f.date), f.readTime ? `${f.readTime} min read` : ''].filter(Boolean).map(esc).join(' · ');
  const byline = `By <b>${esc(f.author)}</b>${dateBits ? ' · ' + dateBits : ''}`;
  const disclaimer = f.hasDisclaimer ? `
        <aside class="callout callout--ai">
          <span class="callout__icon" aria-hidden="true">▲</span>
          <p>${esc(f.disclaimerText || 'AI-generated by Gojo. Not financial advice — do your own research.')}</p>
        </aside>` : '';
  return `<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>${renderHead({ title: f.title, description: f.description })}
</head>
<body>
  <header class="chrome-header" id="site-header" aria-label="Site header"></header>
  <main class="article-page">
    <nav class="breadcrumb" aria-label="Breadcrumb"><ol>${crumbs(f.breadcrumb)}</ol></nav>
    <div class="article-page__grid">
      <article class="article">
        <header class="article__header">
          <span class="kicker">${kicker}</span>
          <h1 class="article__title">${f.headerTitle}</h1>
          <p class="byline">${byline}</p>
        </header>${disclaimer}
        ${f.subtitle ? `<p class="article__lead">${f.subtitle}</p>` : ''}
        <div class="article__content">${f.contentHtml}</div>
        ${f.stepNavHtml || ''}
      </article>
      <aside class="article-rail" id="article-rail" data-url="${esc(f.url)}" data-ticker="${esc(f.ticker)}" data-section="${esc(f.section)}"></aside>
    </div>
  </main>
  <footer class="chrome-footer" id="site-footer" aria-label="Site footer"></footer>
  <script type="module" src="/resources/js/chrome.mjs"></script>
  <script type="module" src="/resources/js/search.mjs"></script>
  <script type="module" src="/resources/js/article.mjs"></script>
</body>
</html>
`;
}
